### ISSUE TITLE
writing a null string to the XML writer throws exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BH22/ipddump#13]
```
When exporting memos as XML, I have some memos which only have a title and 
no text.  This throws an exception when adding a null text.

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: 
Adding text to an XML document must not be null
    at org.dom4j.DocumentFactory.createText(DocumentFactory.java:174)
    at org.dom4j.tree.AbstractElement.addText(AbstractElement.java:899)
    at 
org.quaternions.ipddump.writers.MemosWriters.MemosToXML(MemosWriters.java:1
72)
    at 
gui.IpdDump_NewGUI.saveAsMenuItemActionPerformed(IpdDump_NewGUI.java:700)
...


```

Original issue reported on code.google.com by `borkh...@gmail.com` on 2 Jul 2009 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
Fixed as of r79
```

Original comment by `jimdaska...@gmail.com` on 2 Jul 2009 at 10:52
- Changed state: **Fixed**
