### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 395, Size: 78

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BH22/ipddump#2]
```
Hi
I appreciate your work, it's an extremely interesting project counting on
the number of blackberrys that are used nowadays.

I had a problem running your jar with those parameters

java -jar ipddump-0.1.0.jar Backup-\(2009-05-18\).ipd 

on this platform

java version "1.6.0_07"
Java(TM) SE Runtime Environment (build 1.6.0_07-b06-153)
Java HotSpot(TM) 64-Bit Server VM (build 1.6.0_07-b06-57, mixed mode)

but got this error (it seems it tried to access an index array which is
bigger than the maximum allowed one)

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 395,
Size: 78
        at java.util.LinkedList.entry(LinkedList.java:365)
        at java.util.LinkedList.get(LinkedList.java:315)
        at org.quaternions.ipddump.data.Database.createRecord(Database.java:85)
        at org.quaternions.ipddump.Main.parse(Main.java:177)
        at org.quaternions.ipddump.Main.main(Main.java:36)

Could you easily point me to the problem so that I could fix it by myself?
It's not a really huge backup (1,6MB, like 1000 SMS archived)

Thanks
Nicola
```

Original issue reported on code.google.com by `nicolabe...@gmail.com` on 18 May 2009 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem.
```

Original comment by `jimdaska...@gmail.com` on 27 May 2009 at 9:32

**Comment by GoogleCodeExporter** [comment]
```
I have fixed it.

On the InteractivePagerBackup.java needs to be changed as this:
//////////////////////////////
public Record createRecord( int dbIndex, int version, int uid, int length )
   {


      if (databases.size()>=dbIndex &&("SMS Messages".equals( databases.get( dbIndex ))))
      {
         SMSMessage record = new SMSMessage( dbIndex, version, uid, length );
         smsRecords.add( record );
         return record;
      }
      else
      {
         return new DummyRecord( dbIndex, version, uid, length );
      }
   }
////////////////////////////////////v
```

Original comment by `jimdaska...@gmail.com` on 27 May 2009 at 9:52

**Comment by GoogleCodeExporter** [comment]
```
I fixed it using a sms-only backup (no contacts, multimedia, etc)
```

Original comment by `nicolabe...@gmail.com` on 27 May 2009 at 10:00

**Comment by GoogleCodeExporter** [comment]
```
Get it fixed and with GUI

Here is the link
http://dl.getdropbox.com/u/897187/IpdDump-WithGUI.jar 
```

Original comment by `jimdaska...@gmail.com` on 27 May 2009 at 10:34

**Comment by GoogleCodeExporter** [comment]
```
I have reproduced the error and I'm working on fixing it.  jimdaskalakis01, I 
tried
the same thing you did, but that won't work.  Sometimes the database record 
size is
0xffff.  It's possible that I don't fully understand the IPD spec, but it's more
likely that I have an error in my parser.  The work-around is exactly what
nicolabeghin suggested, an sms-only backup.
```

Original comment by `borkh...@gmail.com` on 27 May 2009 at 11:22
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
it works almost perfect for me. Some of my backup files do not work thought for 
no
apparent reason at all..
I have suggestions and some other improvements on your code... I believe that 
with
some work this would be a really good program!

```

Original comment by `jimdaska...@gmail.com` on 27 May 2009 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
This bug seems to be resolved in r23.  I don't consider it completely closed 
because 
my "fix" was a hack.  However, the SMS messages are output without an 
exception.  
I'll keep an eye out for this issue in the future.
```

Original comment by `borkh...@gmail.com` on 2 Jun 2009 at 1:00
- Changed state: **Fixed**
