### ISSUE TITLE
IPDDump 0.3 won't open SMS - says "WORKING...be patient" indefinitely - 0.2.5 works.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BH22/ipddump#32]
```
I have a IPD backup that 0.2.5 will open, but 0.3 will not.

Under 0.3, it simply says "WORKING... be patient!" in the status bar, and sits 
there indefinitely (at least 10 minutes, I didn't wait longer than that).

Under 0.2.5, it opens near instantly.

I've tried this with both a full IPD backup, as well as only the SMS messages, 
as that's what I wanted to extract from this backup. I suspect it may be the 
SMS messages causing issues, I'm not sure if this is a known regression, but I 
can send you the IPD file if that would help. (Not going to attach it here 
publicly, obviously...lol).

```

Original issue reported on code.google.com by `victorh...@gmail.com` on 23 Jun 2010 at 1:22

**Comment by GoogleCodeExporter** [comment]
```
Yes please sent me the ipd since i cannot reproduce the problem... the mail is 
jimdaskalakis01@gmail.com
```

Original comment by `jimdaska...@gmail.com` on 23 Jun 2010 at 1:21
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `jimdaska...@gmail.com` on 10 Jul 2010 at 10:42
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
heya,

I just hit this issue with another .IPD backup.

I tried with a backup of just the SMS messages, around 900 of them.

On version 2.5, it loads the SMSes fine.

On version 3.0 RC2, the progress bar completes, then it just says "WORKING...be 
patient".

In the command-prompt it says:

C:\Documents and Settings\hooivic\My Documents\Downloads>java -jar "IpdDump 0.3
RC2.jar"
Version: 2 -- LineFeed: a
0: SMS Messages,
Exception in thread "Thread-5" java.lang.NoClassDefFoundError: org/dom4j/Documen
tException
        at ipddump.tools.HistoryMaker.<init>(HistoryMaker.java:42)
        at gui.IpdDump_NewGUI$37.run(IpdDump_NewGUI.java:906)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.dom4j.DocumentException
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClassInternal(Unknown Source)
        ... 3 more

Cheers,
Victor
```

Original comment by `victorh...@gmail.com` on 19 Jul 2010 at 5:40

**Comment by GoogleCodeExporter** [comment]
```
I am trying to fix this as we speak..
```

Original comment by `jimdaska...@gmail.com` on 20 Jul 2010 at 12:24
